Namespace(mode=['alpaca'], base_model='meta-llama/Llama-2-7b-hf', template_name='barebone', total_bsz=64, epoch=3, lr=2e-05, data_path='', task_name='oasst1', tuned_dir='./cache', use_peft=False, lora_r=16, lora_alpha=32)
num gpus:  8
Running 1/1: deepspeed --num_gpus=8 train.py --deepspeed ../deepspeed_config/zero3.json --bf16 --tf32=True
        --model_name_or_path meta-llama/Llama-2-7b-hf --data_path ../data/stanford_alpaca/oasst1_data.json
        --output_dir /fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned
        --num_train_epochs 3
        --per_device_train_batch_size 10
        --per_device_eval_batch_size 4
        --gradient_accumulation_steps 1
        --gradient_checkpointing=True
        --evaluation_strategy=no
        --save_strategy=steps
        --save_steps 500
        --save_total_limit 1
        --learning_rate 2e-6
        --weight_decay 0.
        --report_to tensorboard
        --warmup_ratio 0.03
        --lr_scheduler_type=cosine
        --logging_steps 1
        --use_peft False 
        --lora_r 16 --lora_alpha 32
['deepspeed', '--num_gpus=8', 'train.py', '--deepspeed', '../deepspeed_config/zero3.json', '--bf16', '--tf32=True', '--model_name_or_path', 'meta-llama/Llama-2-7b-hf', '--data_path', '../data/stanford_alpaca/oasst1_data.json', '--output_dir', '/fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned', '--num_train_epochs', '3', '--per_device_train_batch_size', '10', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--gradient_checkpointing=True', '--evaluation_strategy=no', '--save_strategy=steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--report_to', 'tensorboard', '--warmup_ratio', '0.03', '--lr_scheduler_type=cosine', '--logging_steps', '1', '--use_peft', 'False', '--lora_r', '16', '--lora_alpha', '32']
[2024-08-28 18:12:24,697] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
[93m [WARNING] [0m using untested triton version (2.3.0), only 1.0.0 is known to be compatible
[2024-08-28 18:12:32,683] [WARNING] [runner.py:202:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
Detected CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 but ignoring it because one or several of --include/--exclude/--num_gpus/--num_nodes cl args were used. If you want to use CUDA_VISIBLE_DEVICES don't pass any of these arguments to deepspeed.
[2024-08-28 18:12:32,683] [INFO] [runner.py:568:main] cmd = /data/home/yunyun/miniconda3/envs/newtorch2/bin/python3.11 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMCwgMSwgMiwgMywgNCwgNSwgNiwgN119 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None train.py --deepspeed ../deepspeed_config/zero3.json --bf16 --tf32=True --model_name_or_path meta-llama/Llama-2-7b-hf --data_path ../data/stanford_alpaca/oasst1_data.json --output_dir /fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned --num_train_epochs 3 --per_device_train_batch_size 10 --per_device_eval_batch_size 4 --gradient_accumulation_steps 1 --gradient_checkpointing=True --evaluation_strategy=no --save_strategy=steps --save_steps 500 --save_total_limit 1 --learning_rate 2e-6 --weight_decay 0. --report_to tensorboard --warmup_ratio 0.03 --lr_scheduler_type=cosine --logging_steps 1 --use_peft False --lora_r 16 --lora_alpha 32
[2024-08-28 18:12:35,188] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
[93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
[93m [WARNING] [0m async_io: please install the libaio-dev package with apt
[93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
[93m [WARNING] [0m Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
[93m [WARNING] [0m sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
[93m [WARNING] [0m using untested triton version (2.3.0), only 1.0.0 is known to be compatible
[2024-08-28 18:12:38,592] [INFO] [launch.py:139:main] 0 NCCL_ASYNC_ERROR_HANDLING=1
[2024-08-28 18:12:38,592] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]}
[2024-08-28 18:12:38,592] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=8, node_rank=0
[2024-08-28 18:12:38,592] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0, 1, 2, 3, 4, 5, 6, 7]})
[2024-08-28 18:12:38,592] [INFO] [launch.py:164:main] dist_world_size=8
[2024-08-28 18:12:38,592] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
[2024-08-28 18:12:38,593] [INFO] [launch.py:256:main] process 3549597 spawned with command: ['/data/home/yunyun/miniconda3/envs/newtorch2/bin/python3.11', '-u', 'train.py', '--local_rank=0', '--deepspeed', '../deepspeed_config/zero3.json', '--bf16', '--tf32=True', '--model_name_or_path', 'meta-llama/Llama-2-7b-hf', '--data_path', '../data/stanford_alpaca/oasst1_data.json', '--output_dir', '/fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned', '--num_train_epochs', '3', '--per_device_train_batch_size', '10', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--gradient_checkpointing=True', '--evaluation_strategy=no', '--save_strategy=steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--report_to', 'tensorboard', '--warmup_ratio', '0.03', '--lr_scheduler_type=cosine', '--logging_steps', '1', '--use_peft', 'False', '--lora_r', '16', '--lora_alpha', '32']
[2024-08-28 18:12:38,594] [INFO] [launch.py:256:main] process 3549598 spawned with command: ['/data/home/yunyun/miniconda3/envs/newtorch2/bin/python3.11', '-u', 'train.py', '--local_rank=1', '--deepspeed', '../deepspeed_config/zero3.json', '--bf16', '--tf32=True', '--model_name_or_path', 'meta-llama/Llama-2-7b-hf', '--data_path', '../data/stanford_alpaca/oasst1_data.json', '--output_dir', '/fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned', '--num_train_epochs', '3', '--per_device_train_batch_size', '10', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--gradient_checkpointing=True', '--evaluation_strategy=no', '--save_strategy=steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--report_to', 'tensorboard', '--warmup_ratio', '0.03', '--lr_scheduler_type=cosine', '--logging_steps', '1', '--use_peft', 'False', '--lora_r', '16', '--lora_alpha', '32']
[2024-08-28 18:12:38,594] [INFO] [launch.py:256:main] process 3549599 spawned with command: ['/data/home/yunyun/miniconda3/envs/newtorch2/bin/python3.11', '-u', 'train.py', '--local_rank=2', '--deepspeed', '../deepspeed_config/zero3.json', '--bf16', '--tf32=True', '--model_name_or_path', 'meta-llama/Llama-2-7b-hf', '--data_path', '../data/stanford_alpaca/oasst1_data.json', '--output_dir', '/fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned', '--num_train_epochs', '3', '--per_device_train_batch_size', '10', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--gradient_checkpointing=True', '--evaluation_strategy=no', '--save_strategy=steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--report_to', 'tensorboard', '--warmup_ratio', '0.03', '--lr_scheduler_type=cosine', '--logging_steps', '1', '--use_peft', 'False', '--lora_r', '16', '--lora_alpha', '32']
[2024-08-28 18:12:38,595] [INFO] [launch.py:256:main] process 3549600 spawned with command: ['/data/home/yunyun/miniconda3/envs/newtorch2/bin/python3.11', '-u', 'train.py', '--local_rank=3', '--deepspeed', '../deepspeed_config/zero3.json', '--bf16', '--tf32=True', '--model_name_or_path', 'meta-llama/Llama-2-7b-hf', '--data_path', '../data/stanford_alpaca/oasst1_data.json', '--output_dir', '/fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned', '--num_train_epochs', '3', '--per_device_train_batch_size', '10', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--gradient_checkpointing=True', '--evaluation_strategy=no', '--save_strategy=steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--report_to', 'tensorboard', '--warmup_ratio', '0.03', '--lr_scheduler_type=cosine', '--logging_steps', '1', '--use_peft', 'False', '--lora_r', '16', '--lora_alpha', '32']
[2024-08-28 18:12:38,595] [INFO] [launch.py:256:main] process 3549601 spawned with command: ['/data/home/yunyun/miniconda3/envs/newtorch2/bin/python3.11', '-u', 'train.py', '--local_rank=4', '--deepspeed', '../deepspeed_config/zero3.json', '--bf16', '--tf32=True', '--model_name_or_path', 'meta-llama/Llama-2-7b-hf', '--data_path', '../data/stanford_alpaca/oasst1_data.json', '--output_dir', '/fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned', '--num_train_epochs', '3', '--per_device_train_batch_size', '10', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--gradient_checkpointing=True', '--evaluation_strategy=no', '--save_strategy=steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--report_to', 'tensorboard', '--warmup_ratio', '0.03', '--lr_scheduler_type=cosine', '--logging_steps', '1', '--use_peft', 'False', '--lora_r', '16', '--lora_alpha', '32']
[2024-08-28 18:12:38,596] [INFO] [launch.py:256:main] process 3549602 spawned with command: ['/data/home/yunyun/miniconda3/envs/newtorch2/bin/python3.11', '-u', 'train.py', '--local_rank=5', '--deepspeed', '../deepspeed_config/zero3.json', '--bf16', '--tf32=True', '--model_name_or_path', 'meta-llama/Llama-2-7b-hf', '--data_path', '../data/stanford_alpaca/oasst1_data.json', '--output_dir', '/fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned', '--num_train_epochs', '3', '--per_device_train_batch_size', '10', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--gradient_checkpointing=True', '--evaluation_strategy=no', '--save_strategy=steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--report_to', 'tensorboard', '--warmup_ratio', '0.03', '--lr_scheduler_type=cosine', '--logging_steps', '1', '--use_peft', 'False', '--lora_r', '16', '--lora_alpha', '32']
[2024-08-28 18:12:38,596] [INFO] [launch.py:256:main] process 3549603 spawned with command: ['/data/home/yunyun/miniconda3/envs/newtorch2/bin/python3.11', '-u', 'train.py', '--local_rank=6', '--deepspeed', '../deepspeed_config/zero3.json', '--bf16', '--tf32=True', '--model_name_or_path', 'meta-llama/Llama-2-7b-hf', '--data_path', '../data/stanford_alpaca/oasst1_data.json', '--output_dir', '/fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned', '--num_train_epochs', '3', '--per_device_train_batch_size', '10', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--gradient_checkpointing=True', '--evaluation_strategy=no', '--save_strategy=steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--report_to', 'tensorboard', '--warmup_ratio', '0.03', '--lr_scheduler_type=cosine', '--logging_steps', '1', '--use_peft', 'False', '--lora_r', '16', '--lora_alpha', '32']
[2024-08-28 18:12:38,597] [INFO] [launch.py:256:main] process 3549604 spawned with command: ['/data/home/yunyun/miniconda3/envs/newtorch2/bin/python3.11', '-u', 'train.py', '--local_rank=7', '--deepspeed', '../deepspeed_config/zero3.json', '--bf16', '--tf32=True', '--model_name_or_path', 'meta-llama/Llama-2-7b-hf', '--data_path', '../data/stanford_alpaca/oasst1_data.json', '--output_dir', '/fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned', '--num_train_epochs', '3', '--per_device_train_batch_size', '10', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--gradient_checkpointing=True', '--evaluation_strategy=no', '--save_strategy=steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--report_to', 'tensorboard', '--warmup_ratio', '0.03', '--lr_scheduler_type=cosine', '--logging_steps', '1', '--use_peft', 'False', '--lora_r', '16', '--lora_alpha', '32']
/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
2024-08-28 18:12:50.408048: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-28 18:12:50.408041: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-28 18:12:50.408040: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-28 18:12:50.408051: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-28 18:12:50.408063: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-28 18:12:50.408063: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-28 18:12:50.408058: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-28 18:12:50.408072: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-28 18:12:50.624566: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-28 18:12:50.624566: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-28 18:12:50.624574: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-28 18:12:50.624577: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-28 18:12:50.624582: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-28 18:12:50.624581: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-28 18:12:50.624586: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-28 18:12:50.624585: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-28 18:12:50.681389: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-28 18:12:50.681390: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-28 18:12:50.681396: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-28 18:12:50.681393: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-28 18:12:50.681398: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-28 18:12:50.681396: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-28 18:12:50.681403: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-28 18:12:50.681415: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-28 18:12:51.143291: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-28 18:12:51.143288: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-28 18:12:51.143290: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-28 18:12:51.143286: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-28 18:12:51.143286: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-28 18:12:51.143295: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-28 18:12:51.143310: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-28 18:12:51.143310: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-28 18:12:56.191945: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-08-28 18:12:56.191975: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-08-28 18:12:56.192055: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-08-28 18:12:56.192065: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-08-28 18:12:56.192083: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-08-28 18:12:56.192151: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-08-28 18:12:56.192157: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-08-28 18:12:56.192163: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 22, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 22, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 22, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 22, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 22, in <module>
Traceback (most recent call last):
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 22, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 22, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 22, in <module>
        import tf_keras as kerasimport tf_keras as keras            
    
    import tf_keras as kerasimport tf_keras as kerasimport tf_keras as kerasimport tf_keras as kerasModuleNotFoundErrorimport tf_keras as keras



: ModuleNotFoundError
No module named 'tf_keras': ModuleNotFoundErrorModuleNotFoundErrorModuleNotFoundError
ModuleNotFoundErrorNo module named 'tf_keras': : : ModuleNotFoundError    : 
No module named 'tf_keras'No module named 'tf_keras'No module named 'tf_keras': import tf_keras as keras
No module named 'tf_keras'


No module named 'tf_keras'



During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

ModuleNotFoundErrorDuring handling of the above exception, another exception occurred:

: 



During handling of the above exception, another exception occurred:
No module named 'tf_keras'
Traceback (most recent call last):

During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:
Traceback (most recent call last):


Traceback (most recent call last):



  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
Traceback (most recent call last):
Traceback (most recent call last):
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module

  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
Traceback (most recent call last):
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
    return importlib.import_module("." + module_name, self.__name__)                
return importlib.import_module("." + module_name, self.__name__)    return importlib.import_module("." + module_name, self.__name__)return importlib.import_module("." + module_name, self.__name__)return importlib.import_module("." + module_name, self.__name__)    
return importlib.import_module("." + module_name, self.__name__)


return importlib.import_module("." + module_name, self.__name__) 
 
                               return importlib.import_module("." + module_name, self.__name__)       
                                     ^    ^  ^  ^^^ ^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module

^^

^
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module

  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^^^
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)        return _bootstrap._gcd_import(name[level:], package, level)    
return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)        
return _bootstrap._gcd_import(name[level:], package, level)

return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)
 

               return _bootstrap._gcd_import(name[level:], package, level)       
                                                        ^     ^ ^^ ^  ^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^
^
^
^^^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import



  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/modeling_tf_utils.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/modeling_tf_utils.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/modeling_tf_utils.py", line 38, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/modeling_tf_utils.py", line 38, in <module>
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/modeling_tf_utils.py", line 38, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/modeling_tf_utils.py", line 38, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/modeling_tf_utils.py", line 38, in <module>
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/modeling_tf_utils.py", line 38, in <module>
        from .activations_tf import get_tf_activationfrom .activations_tf import get_tf_activation

  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 27, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 27, in <module>
    raise ValueError(
ValueError: Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
    from .activations_tf import get_tf_activation                
from .activations_tf import get_tf_activationfrom .activations_tf import get_tf_activationfrom .activations_tf import get_tf_activationfrom .activations_tf import get_tf_activation
    


  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 27, in <module>
raise ValueError(
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 27, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 27, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 27, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 27, in <module>
    ValueErrorfrom .activations_tf import get_tf_activation: 
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.

  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/activations_tf.py", line 27, in <module>
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
               raise ValueError(^
^^ValueError^: ^Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^
^^
^^The above exception was the direct cause of the following exception:
^^
^^Traceback (most recent call last):
^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
^^^^^    ^return importlib.import_module("." + module_name, self.__name__)^
^^^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^        ^        ^raise ValueError(raise ValueError(^raise ValueError(raise ValueError(^

^

^^^    ValueErrorValueError^ValueErrorValueError^return importlib.import_module("." + module_name, self.__name__): :     ^: : ^
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.raise ValueError(^Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^


^

^ 
^
^
 ValueError^
^ The above exception was the direct cause of the following exception:
: ^The above exception was the direct cause of the following exception:
^The above exception was the direct cause of the following exception:
 Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^The above exception was the direct cause of the following exception:
^
 
^
^
 ^

Traceback (most recent call last):
 
^Traceback (most recent call last):
Traceback (most recent call last):
 ^Traceback (most recent call last):
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
 The above exception was the direct cause of the following exception:
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
 ^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
 
^^^^Traceback (most recent call last):
^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^return _bootstrap._gcd_import(name[level:], package, level)^^
^^^^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^
 ^ ^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^^^^^^    ^^    return importlib.import_module("." + module_name, self.__name__)^        ^return importlib.import_module("." + module_name, self.__name__)
^return importlib.import_module("." + module_name, self.__name__)return importlib.import_module("." + module_name, self.__name__)^
^

^^ ^^   ^ ^   ^ ^   ^ ^        ^ ^      return importlib.import_module("." + module_name, self.__name__) ^ ^return _bootstrap._gcd_import(name[level:], package, level)  
 ^ ^
   ^ ^    ^ ^     ^ ^^    ^ ^^    ^ ^^ ^^ ^^^^ ^^ ^^^^ ^^ ^^^^ ^^ 
^^^ ^^ ^^^ ^^   File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^^^ ^^ ^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^^^^^return _bootstrap._gcd_import(name[level:], package, level)^^^^^^^
^^^^^^^^^^^^^^^ ^^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^^^^^^^^^^^^^^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^^^^^^^^^^^^^^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
^^^^^^^^^^^^^^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
^^^^^^^^^^^^^^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
^^^^^^^^^^^^^^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
^^^^^^^^^^^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/integrations/integration_utils.py", line 36, in <module>
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^^^^^^^

^
^^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module

  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^^^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^^^^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^^
^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    ^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)    ^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked

from .. import PreTrainedModel, TFPreTrainedModel^
^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
 ^ ^      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
 ^return _bootstrap._gcd_import(name[level:], package, level)
 ^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/integrations/integration_utils.py", line 36, in <module>
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
         ^return _bootstrap._gcd_import(name[level:], package, level)return _bootstrap._gcd_import(name[level:], package, level)  ^

  ^  ^    ^        ^ return _bootstrap._gcd_import(name[level:], package, level)   ^ 
^  ^ ^  
 ^        ^   from .. import PreTrainedModel, TFPreTrainedModel  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
 ^   
 ^      ^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
 ^ module = self._get_module(self._class_to_module[name]) ^   File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^ 
 ^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
^^ ^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^ ^ ^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
^^ ^ ^^^ ^ ^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
^^ ^ ^^^^^ ^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
^^^^ ^^^^^ ^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/integrations/integration_utils.py", line 36, in <module>
^^^^ ^^^^^ ^^^^^ ^^^^^ ^^^^    ^ ^^^^module = self._get_module(self._class_to_module[name])^ ^^^^
^^^^^^^^^^^^ ^^^^^^ ^^    ^^^^ ^^from .. import PreTrainedModel, TFPreTrainedModel^^^^ ^^
^^^^ ^^^^^^ ^^^  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^^^ ^^^^^^ ^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^^^^^module = self._get_module(self._class_to_module[name])^^^^^^^
^^^^^^^^^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ 
^^^^^^ ^^^^^^   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^^^^^^ ^^^^^^   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^^^^^^ ^^^^
^   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
^^^^^ ^^^^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import

^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
^^
^^^^^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
^^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^^^^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
^^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^^
^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/integrations/integration_utils.py", line 36, in <module>
^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked

^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
^^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
^^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/integrations/integration_utils.py", line 36, in <module>
^^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/integrations/integration_utils.py", line 36, in <module>
^^      File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/integrations/integration_utils.py", line 36, in <module>
^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
^from .. import PreTrainedModel, TFPreTrainedModel^^
^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/integrations/integration_utils.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^^^^      File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^^from .. import PreTrainedModel, TFPreTrainedModel
^
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^    ^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
raise RuntimeError(^
^^    RuntimeError^from .. import PreTrainedModel, TFPreTrainedModel: ^
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^
^  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^The above exception was the direct cause of the following exception:
^^
    ^from .. import PreTrainedModel, TFPreTrainedModel^Traceback (most recent call last):

^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module

  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
    from .. import PreTrainedModel, TFPreTrainedModel
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
        raise RuntimeError(module = self._get_module(self._class_to_module[name])

RuntimeError: Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`. 
  
  The above exception was the direct cause of the following exception:
              
     module = self._get_module(self._class_to_module[name])    return importlib.import_module("." + module_name, self.__name__)module = self._get_module(self._class_to_module[name])raise RuntimeError( 
module = self._get_module(self._class_to_module[name])

Traceback (most recent call last):

 
        RuntimeError  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
 module = self._get_module(self._class_to_module[name])   :   
   Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^    
^     ^     
^     ^     The above exception was the direct cause of the following exception:
^     ^     
^     ^   ^ Traceback (most recent call last):
^       ^ ^return importlib.import_module("." + module_name, self.__name__) ^ ^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
^
 ^ ^^^^^ ^^^^ ^ ^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^    ^^ ^^^^return importlib.import_module("." + module_name, self.__name__)^^ ^^^^
^^^^^^^^^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^
^^^
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
    ^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
raise RuntimeError(^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^
^^^^^
^^RuntimeError^^^: ^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^
^
^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^
^^^^The above exception was the direct cause of the following exception:
^^^^
^^^^Traceback (most recent call last):
^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
^^^^^^^^^^^    ^^        raise RuntimeError(^^raise RuntimeError(raise RuntimeError(
^


^    RuntimeError^RuntimeError  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level): RuntimeError^: return importlib.import_module("." + module_name, self.__name__)
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.: ^Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.

Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^
 
^
  ^
      
^The above exception was the direct cause of the following exception:
raise RuntimeError(  ^The above exception was the direct cause of the following exception:

  The above exception was the direct cause of the following exception:
^
  ^
RuntimeError  

Traceback (most recent call last):
:       return _bootstrap._gcd_import(name[level:], package, level)Traceback (most recent call last):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.  Traceback (most recent call last):
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module


    File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
    File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module

 ^  ^^The above exception was the direct cause of the following exception:
 ^^ ^^
 ^^ ^^Traceback (most recent call last):
 ^^ ^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
 ^^ ^^ ^^^^^^^^^^^    ^^^return _bootstrap._gcd_import(name[level:], package, level)^^^
^^^^^^^ ^    ^    ^ ^return importlib.import_module("." + module_name, self.__name__)^return importlib.import_module("." + module_name, self.__name__)^ ^
^
^ ^^^     ^^ ^  return importlib.import_module("." + module_name, self.__name__)^^ ^  
^^ ^      ^^ ^  return importlib.import_module("." + module_name, self.__name__)^ ^ ^  
^ ^ ^  ^ ^ ^ ^^  ^ ^ ^^  ^ ^ ^^  ^ ^ ^^  ^ ^ ^^  ^^^^^^  ^^^^^^  ^^^^^^  ^^^^^^ ^^^^^^^ ^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^^^^^^^^^^^^^^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^^^^^^^^
^^^^^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
^^^^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^^^^^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
^^^^^^^^^^^^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
^^^
^^^^^^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
^^^^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^^^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/trainer.py", line 42, in <module>
^^^^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^^^^^^^^^^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
    ^^^^^return _bootstrap._gcd_import(name[level:], package, level)^^^^^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked

^^^^^^^^^^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
^ ^^^^^ ^^^^^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
^ ^^^^^ ^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/trainer.py", line 42, in <module>
^ ^^^^^ ^^^^^ ^^^^^^ ^^^
    ^ ^^^from .integrations import (^ ^^^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import

^ ^^^    ^^^^^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
from .integrations import (  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^^^^^
^^^^^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^^^^^  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^^^^^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
^^^^
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^^^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^^^^^
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/trainer.py", line 42, in <module>
^^
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/importlib/__init__.py", line 126, in import_module
^^^^^^^^^    ^module = self._get_module(self._class_to_module[name])^
^^^ ^ ^ ^ ^^     ^     return _bootstrap._gcd_import(name[level:], package, level)^return _bootstrap._gcd_import(name[level:], package, level)     
^
module = self._get_module(self._class_to_module[name]) ^
     ^       from .integrations import (^ return _bootstrap._gcd_import(name[level:], package, level)   
^ 
   ^      File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^   ^     ^   ^return _bootstrap._gcd_import(name[level:], package, level)   File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^   ^
 ^   ^ ^   ^  ^   ^  ^   ^  ^^^ ^  ^^^ ^  ^^^ ^  ^^^ ^^ 
^^^^^ ^^^^^       File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^^^^^ module = self._get_module(self._class_to_module[name])^^^^^ 
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^^^^^^^^^^^^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
 ^^^^^^ ^^^^^^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
 ^^^^^^ ^^^^^^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
 ^^^^^^ ^^^^^^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
 ^^^^^^ ^^^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/trainer.py", line 42, in <module>
 ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^^^^^^^from .integrations import (^^^^^^^
^^^^^^^^^^^^^^^  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^^^^^^^^^^^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^^^^^^^^^^^^^^^^^^^^^    ^^^^^^module = self._get_module(self._class_to_module[name])^^^^^^
^^^^^^^^^^^^^ ^^
^^^ ^^^^
 ^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^^ ^^    ^^  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
 
^raise RuntimeError(^^ ^
^^  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^^^ ^RuntimeError^^  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load

: ^^ Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import

^^   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked

^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
 
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
^The above exception was the direct cause of the following exception:
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
^    ^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/trainer.py", line 42, in <module>
raise RuntimeError(^
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
^
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/trainer.py", line 42, in <module>
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
^^Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
^RuntimeError^  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked

: ^  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/yunyun/llm_fingerprinting/stanford_alpaca/train.py", line 24, in <module>
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module

^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/trainer.py", line 42, in <module>
^
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
^^The above exception was the direct cause of the following exception:
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/trainer.py", line 42, in <module>
^^    
^from .integrations import (^
Traceback (most recent call last):
^^  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/yunyun/llm_fingerprinting/stanford_alpaca/train.py", line 24, in <module>
^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^^^^^^^^    ^    from .integrations import (^from .integrations import (
^
^      File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^raise RuntimeError(  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^RuntimeError^: ^    Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^from .integrations import (
^
^        
^from transformers import Trainermodule = self._get_module(self._class_to_module[name])  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^

The above exception was the direct cause of the following exception:
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__


  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  Traceback (most recent call last):
      File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
 from transformers import Trainer   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/yunyun/llm_fingerprinting/stanford_alpaca/train.py", line 24, in <module>

     module = self._get_module(self._class_to_module[name])   File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist

    File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
            module = self._get_module(self._class_to_module[name])              
^raise RuntimeError( module = self._get_module(self._class_to_module[name])module = self._get_module(self._class_to_module[name])^
 

^  ^ RuntimeError  ^  :   ^^  Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.      ^      
  from transformers import Trainer^ module = self._get_module(self._class_to_module[name])   
^ 
 
^ ^  ^   File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^   The above exception was the direct cause of the following exception:
^ ^   ^   File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^   
^ ^   ^ ^   Traceback (most recent call last):
^ ^ ^ ^ ^ ^   File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/yunyun/llm_fingerprinting/stanford_alpaca/train.py", line 24, in <module>
^^^^^ ^^^^^ ^^^^^ ^^^^^ ^^^^^ ^^^^^ ^^^^^^^^    ^^^^^^module = self._get_module(self._class_to_module[name])^^^^^^
^^    ^^^^^^from transformers import Trainer^^^^^ ^
^^^^^ ^^^^^^ ^^  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^^^^ ^^^^^^ ^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^^^^^^^^^^^^^^    ^^^^^^^module = self._get_module(self._class_to_module[name])
^^^^^^
^^^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^^^^ ^^^
^^ ^^^^^ ^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^ ^^    ^^^ ^^raise RuntimeError(^^^ ^^
^^^ ^^^^^^^
RuntimeError^^^^^: ^
^^
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^^^
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^^
^^^^^^    ^The above exception was the direct cause of the following exception:
^^raise RuntimeError(^
^
^
^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^RuntimeError^Traceback (most recent call last):
^: ^^Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^  File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/yunyun/llm_fingerprinting/stanford_alpaca/train.py", line 24, in <module>
^
^^^^
^^^^The above exception was the direct cause of the following exception:
^^^^
^^^^Traceback (most recent call last):
^^^    ^      File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/yunyun/llm_fingerprinting/stanford_alpaca/train.py", line 24, in <module>
^raise RuntimeError(^raise RuntimeError(^


^RuntimeError^      File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
: RuntimeError^raise RuntimeError(Failed to import transformers.trainer because of the following error (look up to see its traceback):
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.: ^
    
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^from transformers import Trainer
^RuntimeError
^    : 
^raise RuntimeError(Failed to import transformers.trainer because of the following error (look up to see its traceback):
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^

The above exception was the direct cause of the following exception:
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^RuntimeError    
^: from transformers import Trainer
^^Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.Traceback (most recent call last):
    ^
raise RuntimeError(  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
^  File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/yunyun/llm_fingerprinting/stanford_alpaca/train.py", line 24, in <module>

^
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^RuntimeError
The above exception was the direct cause of the following exception:
: Failed to import transformers.trainer because of the following error (look up to see its traceback):
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module

Traceback (most recent call last):
    module = self._get_module(self._class_to_module[name])  File "/opt/hpcaas/.mounts/fs-0301404b74c8d22fd/home/yunyun/llm_fingerprinting/stanford_alpaca/train.py", line 24, in <module>

             ^^^^^^^^^^^^^^    ^from transformers import Trainer^
^^    ^  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
module = self._get_module(self._class_to_module[name])^
^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
^^ ^     ^ from transformers import Trainer^ 
    ^ raise RuntimeError(^   File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist

^ ^   File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
RuntimeError^ : ^ Failed to import transformers.trainer because of the following error (look up to see its traceback):
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^ 
^     ^ module = self._get_module(self._class_to_module[name])^^
^^^^^ ^^ ^^ ^^ ^^ ^^ ^^ ^
 ^ ^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
 ^ ^ ^ ^^^^    ^^module = self._get_module(self._class_to_module[name])^^
^^^^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^     ^^raise RuntimeError(^^^
^^^^^^RuntimeError^^^: ^^^Failed to import transformers.trainer because of the following error (look up to see its traceback):
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.^^^
^^^^^^^^^^^^^^^^
^^^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^^^^^^^^^^^^^^^^^^^^^^^
^^  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
^^^^^^^^^^^^^^^^^
  File "/data/home/yunyun/miniconda3/envs/newtorch2/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
    raise RuntimeError(    
raise RuntimeError(
RuntimeError: RuntimeErrorFailed to import transformers.trainer because of the following error (look up to see its traceback):
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.: 
Failed to import transformers.trainer because of the following error (look up to see its traceback):
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.
    raise RuntimeError(
RuntimeError: Failed to import transformers.trainer because of the following error (look up to see its traceback):
Failed to import transformers.integrations.integration_utils because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
Your currently installed version of Keras is Keras 3, but this is not yet supported in Transformers. Please install the backwards-compatible tf-keras package with `pip install tf-keras`.
[2024-08-28 18:13:10,601] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3549597
[2024-08-28 18:13:10,653] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3549598
[2024-08-28 18:13:10,654] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3549599
[2024-08-28 18:13:10,702] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3549600
[2024-08-28 18:13:10,749] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3549601
[2024-08-28 18:13:10,794] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3549602
[2024-08-28 18:13:10,838] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3549603
[2024-08-28 18:13:10,882] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3549604
[2024-08-28 18:13:10,925] [ERROR] [launch.py:325:sigkill_handler] ['/data/home/yunyun/miniconda3/envs/newtorch2/bin/python3.11', '-u', 'train.py', '--local_rank=7', '--deepspeed', '../deepspeed_config/zero3.json', '--bf16', '--tf32=True', '--model_name_or_path', 'meta-llama/Llama-2-7b-hf', '--data_path', '../data/stanford_alpaca/oasst1_data.json', '--output_dir', '/fsx-project/yunyun/models/meta-llama_Llama2-7b_oasst1_tuned', '--num_train_epochs', '3', '--per_device_train_batch_size', '10', '--per_device_eval_batch_size', '4', '--gradient_accumulation_steps', '1', '--gradient_checkpointing=True', '--evaluation_strategy=no', '--save_strategy=steps', '--save_steps', '500', '--save_total_limit', '1', '--learning_rate', '2e-6', '--weight_decay', '0.', '--report_to', 'tensorboard', '--warmup_ratio', '0.03', '--lr_scheduler_type=cosine', '--logging_steps', '1', '--use_peft', 'False', '--lora_r', '16', '--lora_alpha', '32'] exits with return code = 1
